name: Canadian Centre for Cyber Security YARA Specification

on:
  push:
    paths:
    - YARA/**
  pull_request:
    paths:
    - YARA/**
  workflow_dispatch:

permissions:
  contents: read

jobs:
  Lint:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Canadian Centre for Cyber Security YARA Specification
      uses: actions/checkout@v3
      with:
        repository: CybercentreCanada/CCCS-Yara
        submodules: recursive
        path: cccs
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f cccs/requirements.txt ]; then pip install -r cccs/requirements.txt; fi
        
    - name: Checkout signatures
      uses: actions/checkout@v3
      with:
        path: signatures


    - name: Lint with Canadian Centre for Cyber Security YARA Specification
      run: |
        python cccs/yara_validator_cli.py -n -v -f signatures/YARA/
