name: Canadian Centre for Cyber Security YARA Specification

on:
  push:
    paths:
    - YARA/**
  pull_request:
    paths:
    - YARA/**
  workflow_dispatch:

permissions:
  contents: read

jobs:
  Lint:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install git+https://github.com/CybercentreCanada/CCCS-Yara
    - name: Checkout signatures
      uses: actions/checkout@v3
    - name: Lint with Canadian Centre for Cyber Security YARA Specification
      run: |
        yara_validator -n -v -f $GITHUB_WORKSPACE/YARA/
