name: YARAhub

on:
  push:
    paths:
    - YARA/**
  workflow_dispatch:

permissions:
  contents: read

jobs:
  Package:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Checkout signatures
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f $GITHUB_WORKSPACE/.github/workflows/YARAhub/requirements.txt ]; then pip install -r $GITHUB_WORKSPACE/.github/workflows/YARAhub/requirements.txt; fi


    - name: Convert YARA rules to YARAhub format
      run: |
        mkdir $GITHUB_WORKSPACE/out
        python $GITHUB_WORKSPACE/.github/workflows/YARAhub/YARAhub.py --dir $GITHUB_WORKSPACE/out $GITHUB_WORKSPACE/YARA/*.yar

    - uses: actions/upload-artifact@v3
      with:
        name: YARAhub
        path: ${{ github.workspace }}/out/*.yar
        if-no-files-found: error